# Generated by Django 4.2 on 2024-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masomoapp', '0002_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='member', max_length=50),
        ),
    ]
