# Generated by Django 4.2 on 2024-12-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masomoapp', '0003_remove_member_date_joined_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masomoapp.course'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masomoapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(through='masomoapp.Performance', to='masomoapp.course'),
        ),
    ]
