# Generated by Django 4.2 on 2024-12-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masomoapp', '0007_remove_member_user_student_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
