# Generated by Django 4.2 on 2024-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masomoapp', '0008_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='performance',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='performance',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
