# Generated by Django 4.2 on 2024-12-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masomoapp', '0009_remove_student_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masomoapp.student'),
        ),
    ]
